# https://github.com/tamccullough - questions? twitter @tamccullough

FIRST_NAMES = [
    'Bloody','Torn','Rip','Slash','Render','Smash','Chop','Squish','Squash','Tear','Split','Grind','Burn',
    'Sharp','Bite','Grind','Gnash','Bash','Spike','Plunder','Crush','Clobber','Punish','Burp','Glare'
]
LAST_NAMES = [
    'Claw','Horn','Tooth','Fang','Fist','Gobble','Fire','Dark','Sunder','Destroy','Clawed','Clawing',
    'Horned','Fanged','Gobbled','Bleeding','War','Rendered','Render','Darkclaw','Sharptooth','Darkhorn',
    'Fistclaw','Firetooth','Firefist','Doom','Firefang','Warhorn','Firegobbler','Warfire','Thunderclaw',
]

convert = {
    'torso':{
        1:'forest',
        2:'flame',
        3:'sky',
        4:'night',
    },
    'arms':{
        1:'forest',
        2:'flame',
        3:'sky',
        4:'night',
    },
    'legs':{
        1:'forest',
        2:'flame',
        3:'sky',
        4:'night',
    },
    'head':{
        1:'forest',
        2:'flame',
        3:'sky',
        4:'night',
    },
    'face':{
        1:'zombie',
        2:'toothy',
        3:'jagged',
        4:'frog',
        5:'gator'
    },
    'acc':{
        0:'none',
        1:'dark shades',
        2:'gold round shades',
        3:'gold shades',
        4:'dark round shades',
        5:'double gold earrings',
        6:'double dark earrings',
        7:'uneven dark earrings',
        8:'single gold earrings',
        9:'dark stud earrings',
        10:'gold eye medalion',
        11:'gold skull medalion',
        12:'bronze round shades',
        13:'dark eye medalion',
        14:'dark skull medalion',
        15:'gold dark eye medalion',
        16:'gold dark skull medalion',
        17:'dark/gold studs skull medalion',
        18:'dark/gold earrings eye medalion',
        19:'gold earrings skull medalion',
        20:'dark/gold earrings eye medalion',
        21:'gold shades dark eye medalion',
        22:'bronze round shades gold eye medalion',

    },
    'eyes':{
        1:'blue goat',
        2:'pink goat',
        3:'yellow goat',
        4:'orange cat',
        5:'green long',
        6:'blue red long',
        7:'pink bean',
        8:'black white long',
        9:'yellow slit goat',
        10:'red round',
        11:'blue round',
        12:'blue cat',
        13:'yellow black frog',
        14:'green goat',
        15:'red cat',
        16:'violet goat',
        17:'yellow bean',
        18:'yellow red frog',
    },
    'foot':{
        0:'none',
        1:'blue sandal',
        2:'teal sandal',
        3:'green crocs',
        4:'yellow crocs',
        5:'black red sneakers',
        6:'orange sneakers',
        7:'black sneakers',
        8:'violet sneakers',
        9:'docs red',
        10:'docs black',
        11:'green chucks',
        12:'red chucks',
        13:'violet chucks',
        14:'onyx hightops',
        15:'bees hightops',
        16:'autumn hightops',
    },
    'hat':{
        0:'none',
        1:'red mohawk',
        2:'yellow bowler',
        3:'blood horns',
        4:'ice horns',
        5:'black bowler',
        6:'green flat top',
        7:'red ramone',
        8:'red ball cap',
        9:'goalie',
        10:'skull',
        11:'horned skull',
        12:'orange bowler',
        13:'orange mohawk',
        14:'violet ball cap',
        15:'blue ramone',
        16:'red flat top',
        17:'violet triple hawk',
        18:'yellow triple hawk',
        19:'black ball cap'
    },
    'logo':{
        0:'none',
        1:'skull',
        2:'eye',
        3:'dead',
        4:'DL Metal',
        5:'DL Alt',
        6:'DL Rap',
        7:'DL Block',
        8:'DL Comic 1',
        9:'DL Comic 2',
    },
    'pants':{
        0:'none',
        1:'red plaid',
        2:'yellow plaid',
        3:'straight camouflage',
        4:'blue baggies',
        5:'yellow camouflage baggies',
        6:'dark sweats',
        7:'yellow sweats',
        8:'black stars shorts',
        9:'dark shorts',
        10:'orange stars 80s shorts',
        11:'dark jeans',
        12:'blue argyle pants',
        13:'red argyle pants',
        14:'yellow argyle pants',
        15:'red tights',
        16:'yellow tights',
        17:'blue camouflage sweats',
        18:'yellow puffs sweats',
        19:'violet triangles shorts',
        20:'yellow puffs shorts',
        21:'yellow stars 80s shorts',
        22:'red jeans',
    },
    'socks':{
        0:'none',
        1:'white',
        2:'black',
        3:'white & red stripes',
        4:'red & black stripes',
        5:'black & red stripes',
        6:'red',
    },
    'tattoo':{
        0:'none',
        1:'Eye',
        2:'2 skull DL',
        3:'DL & skull',
        4:'DL & skulls',
        5:'Eye DL',
        6:'Dark Lord',
        7:'Dead skulls',
        8:'Dead skulls & DL'
    },
    'shirt':{
        0:'none',
        1:'green t',
        2:'yellow long',
        3:'dark 80s tris long',
        4:'bright 80s tris t',
        5:'dark hoodie',
        6:'yellow tank',
        7:'red sleeveless',
        8:'red dashes t',
        9:'yellow 80s glygh sleeveless',
        10:'red t yellow long',
        11:'yellow camouflage hoodie',
        12:'blue tank',
        13:'violet 80s tris long',
        14:'yellow t',
        15:'red long',
        16:'red 80s glyph long',
        17:'yellow 80s glyph t',
        18:'red hoodie',
        19:'black tank',
        20:'blue sleeveless',
        21:'magenta dash t',
        22:'yellow sleeveless',
        23: 'yellow t red long',
        24:'red camouflage hoodie',
        25:'red tank',
        26:'yellow 80s glyph long',
    }
}

# query the above dictionary to convert the int values in the dataframe
# into something useful in the item attributes
def get_collection_item(item,num):
    return convert[item][num]
